platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
    pod 'BDGShare'
    pod 'BDGViews'
    pod 'BDGMacros'
    pod 'BDGCategories'
    pod 'BDGScreenshot'
    
    pod 'Blaze'
    pod 'AFNetworking'
    pod 'SVProgressHUD'
    pod 'HockeySDK-Source'
    pod 'DTTJailbreakDetection'
end

target 'Template' do
    shared_pods
end
